name: Binary Builder

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish-app

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install system dependencies
        run: |
          sudo apt install wine mono-complete nsis -y

      - name: Install npm dependencies
        run: npm ci

      # - name: Build binaries
      #   run: npm run make

      - name: Publish binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npm run publish
